; PlatformIO Project Configuration File
;
; Build options: pio run
; Upload options: pio run --target upload
; Monitor options: pio device monitor

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor options
monitor_speed = 115200
monitor_filters = default

; Library dependencies
lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3

