"""
PAde activation utilities - patched for EDGE deployment (no CUDA required).
Auto-generated by setup_ecg_dualnet.py
"""
import torch
from torch import nn

# Import pure PyTorch implementation (no CUDA needed)
from ecg_classification.pade_activation_unit.pytorch_impl import PADEACTIVATION_Function_based


class Swish(torch.autograd.Function):
    @staticmethod
    def forward(ctx, i):
        result = i * i.sigmoid()
        ctx.save_for_backward(result, i)
        return result

    @staticmethod
    def backward(ctx, grad_output):
        result, i = ctx.saved_variables
        sigmoid_x = i.sigmoid()
        return grad_output * (result + sigmoid_x * (1 - result))


swish = Swish.apply


class Swish_module(nn.Module):
    def forward(self, x):
        return swish(x)


ACTIVATION_FUNCTIONS = dict({
    "pade_optimized_leakyrelu_abs": "pade_optimized_leakyrelu_abs",
    "sigmoid": nn.Sigmoid(),
    "relu": nn.ReLU, "selu": nn.SELU, "leakyrelu": nn.LeakyReLU, "celu": nn.CELU,
    "elu": nn.ELU,
    "tanh": nn.Tanh,
    "relu6": nn.ReLU6,
    "swish": Swish_module,
    "softplus": nn.Softplus,
    "prelu": nn.PReLU,
    "rrelu": nn.RReLU
})


class activationfunc():
    def __init__(self, selected_activation_func):
        self.selected_activation_func = selected_activation_func
        assert "pade" in selected_activation_func or selected_activation_func in ACTIVATION_FUNCTIONS, \
            "unknown activation function %s" % selected_activation_func

    def get_activationfunc(self):
        if "pade" in self.selected_activation_func:
            init_coefficients = self.selected_activation_func.replace("_abs", "").replace("_cuda", "")
            return PADEACTIVATION_Function_based(init_coefficients=init_coefficients)
        else:
            return ACTIVATION_FUNCTIONS[self.selected_activation_func]()


def PAU():
    """PAU activation function using pure PyTorch implementation."""
    return PADEACTIVATION_Function_based(init_coefficients="pade_optimized_leakyrelu")
