"""
ECG-DualNet package for EDGE deployment.
Auto-generated by setup_ecg_dualnet.py
"""
from .ecg_dualnet_wrapper import ECGDualNetWrapper, get_pretrained_ecg_dualnet

__all__ = ['ECGDualNetWrapper', 'get_pretrained_ecg_dualnet']
