"""
ECG-DualNet classification module - minimal version for EDGE inference.
Auto-generated by setup_ecg_dualnet.py
"""
# Import models
from ecg_classification.model import ECGCNN, ECGAttNet
# Import model configs
from ecg_classification.config import (
    ECGCNN_CONFIG_S, ECGAttNet_CONFIG_S, 
    ECGCNN_CONFIG_M, ECGAttNet_CONFIG_M,
    ECGCNN_CONFIG_L, ECGAttNet_CONFIG_L, 
    ECGCNN_CONFIG_XL, ECGAttNet_CONFIG_XL,
    ECGAttNet_CONFIG_XXL, ECGAttNet_CONFIG_130M
)

__all__ = [
    'ECGCNN', 'ECGAttNet',
    'ECGCNN_CONFIG_S', 'ECGAttNet_CONFIG_S',
    'ECGCNN_CONFIG_M', 'ECGAttNet_CONFIG_M',
    'ECGCNN_CONFIG_L', 'ECGAttNet_CONFIG_L',
    'ECGCNN_CONFIG_XL', 'ECGAttNet_CONFIG_XL',
    'ECGAttNet_CONFIG_XXL', 'ECGAttNet_CONFIG_130M'
]
