#!/usr/bin/env python3
"""
Setup ECG-DualNet for EDGE
Copies minimal ECG-DualNet code and pretrained weights into EDGE for standalone deployment.
"""

import os
import shutil
import sys
from pathlib import Path

# Paths
EDGE_DIR = Path(__file__).parent.resolve()
ML_DIR = EDGE_DIR.parent / 'ML'
DUALNET_REPO = ML_DIR / 'ecg_dualnet_repo'
EDGE_DUALNET_DIR = EDGE_DIR / 'ecg_dualnet'

# Required files to copy
REQUIRED_FILES = {
    # Source (relative to DUALNET_REPO) -> Destination (relative to EDGE_DUALNET_DIR)
    'ecg_classification/__init__.py': 'ecg_classification/__init__.py',
    'ecg_classification/model.py': 'ecg_classification/model.py',
    'ecg_classification/config.py': 'ecg_classification/config.py',
    'ecg_classification/pade_activation_unit/pytorch_impl.py': 'ecg_classification/pade_activation_unit/pytorch_impl.py',
    'ecg_classification/pade_activation_unit/utils.py': 'ecg_classification/pade_activation_unit/utils.py',
}

# Pretrained model weights
PRETRAINED_WEIGHTS = {
    # Model S (recommended - best balance of size and accuracy)
    'experiments/13_05_2021__01_37_34ECGCNN_S_physio_net_dataset/models/best_model.pt': 
        'pretrained/ECGCNN_S_best_model.pt',
}

# Wrapper file from ML/models
WRAPPER_SOURCE = ML_DIR / 'models' / 'ecg_dualnet_wrapper.py'
WRAPPER_DEST = EDGE_DUALNET_DIR / 'ecg_dualnet_wrapper.py'


def setup_ecg_dualnet(force=False):
    """
    Setup ECG-DualNet in EDGE directory.
    
    Args:
        force: If True, overwrite existing files
        
    Returns:
        True if setup successful
    """
    print("=" * 60)
    print("ECG-DualNet Setup for EDGE")
    print("=" * 60)
    
    # Check if already set up
    if (EDGE_DUALNET_DIR / 'ecg_classification' / 'model.py').exists() and not force:
        print("✓ ECG-DualNet already set up in EDGE")
        return True
    
    # Check if ML directory exists (only works on dev machine)
    if not ML_DIR.exists():
        print("⚠ ML directory not found at:", ML_DIR)
        print("  This is expected on Pi4 deployment.")
        print("  ECG-DualNet should already be in EDGE/ecg_dualnet/")
        
        if EDGE_DUALNET_DIR.exists():
            print("✓ Using existing EDGE/ecg_dualnet/")
            return True
        else:
            print("✗ ERROR: ECG-DualNet not found. Please copy from development machine.")
            return False
    
    print(f"Source: {DUALNET_REPO}")
    print(f"Target: {EDGE_DUALNET_DIR}")
    
    # Create directories
    (EDGE_DUALNET_DIR / 'ecg_classification' / 'pade_activation_unit').mkdir(parents=True, exist_ok=True)
    (EDGE_DUALNET_DIR / 'pretrained').mkdir(parents=True, exist_ok=True)
    
    # Copy required files
    print("\nCopying model code...")
    for src_rel, dst_rel in REQUIRED_FILES.items():
        src = DUALNET_REPO / src_rel
        dst = EDGE_DUALNET_DIR / dst_rel
        
        if src.exists():
            shutil.copy2(src, dst)
            print(f"  ✓ {src_rel}")
        else:
            print(f"  ✗ Missing: {src_rel}")
            return False
    
    # Copy pretrained weights
    print("\nCopying pretrained weights...")
    for src_rel, dst_rel in PRETRAINED_WEIGHTS.items():
        src = DUALNET_REPO / src_rel
        dst = EDGE_DUALNET_DIR / dst_rel
        
        if src.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            size_mb = src.stat().st_size / (1024 * 1024)
            print(f"  ✓ {dst_rel} ({size_mb:.1f} MB)")
        else:
            print(f"  ✗ Missing: {src_rel}")
            print("    ECG-DualNet pretrained weights required.")
            return False
    
    # Copy and modify wrapper
    print("\nCopying wrapper...")
    if WRAPPER_SOURCE.exists():
        # Read original wrapper
        with open(WRAPPER_SOURCE, 'r') as f:
            wrapper_code = f.read()
        
        # Modify the import to use local ecg_classification
        # Original: from ecg_classification import ...
        # We keep this since we're copying ecg_classification locally
        
        # Write to destination
        with open(WRAPPER_DEST, 'w') as f:
            f.write(wrapper_code)
        print(f"  ✓ ecg_dualnet_wrapper.py")
    else:
        print(f"  ✗ Missing: {WRAPPER_SOURCE}")
        return False
    
    # Create __init__.py for ecg_dualnet package
    init_content = '''"""
ECG-DualNet package for EDGE deployment.
Auto-generated by setup_ecg_dualnet.py
"""
from .ecg_dualnet_wrapper import ECGDualNetWrapper, get_pretrained_ecg_dualnet

__all__ = ['ECGDualNetWrapper', 'get_pretrained_ecg_dualnet']
'''
    with open(EDGE_DUALNET_DIR / '__init__.py', 'w') as f:
        f.write(init_content)
    print("  ✓ __init__.py")
    
    # Create __init__.py for pade_activation_unit
    pade_init_content = '''"""PAde activation unit for ECG-DualNet."""
from .pytorch_impl import PADEACTIVATION_Function_based

# Provide PAU function for compatibility
def PAU():
    """Pure PyTorch PAU activation - no CUDA required."""
    return PADEACTIVATION_Function_based(init_coefficients="pade_optimized_leakyrelu")

__all__ = ['PAU', 'PADEACTIVATION_Function_based']
'''
    with open(EDGE_DUALNET_DIR / 'ecg_classification' / 'pade_activation_unit' / '__init__.py', 'w') as f:
        f.write(pade_init_content)
    print("  ✓ pade_activation_unit/__init__.py")
    
    # Create patched utils.py that uses pure PyTorch (no CUDA dependency)
    patched_utils = '''"""
PAde activation utilities - patched for EDGE deployment (no CUDA required).
Auto-generated by setup_ecg_dualnet.py
"""
import torch
from torch import nn

# Import pure PyTorch implementation (no CUDA needed)
from ecg_classification.pade_activation_unit.pytorch_impl import PADEACTIVATION_Function_based


class Swish(torch.autograd.Function):
    @staticmethod
    def forward(ctx, i):
        result = i * i.sigmoid()
        ctx.save_for_backward(result, i)
        return result

    @staticmethod
    def backward(ctx, grad_output):
        result, i = ctx.saved_variables
        sigmoid_x = i.sigmoid()
        return grad_output * (result + sigmoid_x * (1 - result))


swish = Swish.apply


class Swish_module(nn.Module):
    def forward(self, x):
        return swish(x)


ACTIVATION_FUNCTIONS = dict({
    "pade_optimized_leakyrelu_abs": "pade_optimized_leakyrelu_abs",
    "sigmoid": nn.Sigmoid(),
    "relu": nn.ReLU, "selu": nn.SELU, "leakyrelu": nn.LeakyReLU, "celu": nn.CELU,
    "elu": nn.ELU,
    "tanh": nn.Tanh,
    "relu6": nn.ReLU6,
    "swish": Swish_module,
    "softplus": nn.Softplus,
    "prelu": nn.PReLU,
    "rrelu": nn.RReLU
})


class activationfunc():
    def __init__(self, selected_activation_func):
        self.selected_activation_func = selected_activation_func
        assert "pade" in selected_activation_func or selected_activation_func in ACTIVATION_FUNCTIONS, \\
            "unknown activation function %s" % selected_activation_func

    def get_activationfunc(self):
        if "pade" in self.selected_activation_func:
            init_coefficients = self.selected_activation_func.replace("_abs", "").replace("_cuda", "")
            return PADEACTIVATION_Function_based(init_coefficients=init_coefficients)
        else:
            return ACTIVATION_FUNCTIONS[self.selected_activation_func]()


def PAU():
    """PAU activation function using pure PyTorch implementation."""
    return PADEACTIVATION_Function_based(init_coefficients="pade_optimized_leakyrelu")
'''
    with open(EDGE_DUALNET_DIR / 'ecg_classification' / 'pade_activation_unit' / 'utils.py', 'w') as f:
        f.write(patched_utils)
    print("  ✓ utils.py (patched - pure PyTorch, no CUDA)")
    
    # Create minimal __init__.py for ecg_classification (inference only - no dataset/loss modules)
    ecg_class_init = '''"""
ECG-DualNet classification module - minimal version for EDGE inference.
Auto-generated by setup_ecg_dualnet.py
"""
# Import models
from ecg_classification.model import ECGCNN, ECGAttNet
# Import model configs
from ecg_classification.config import (
    ECGCNN_CONFIG_S, ECGAttNet_CONFIG_S, 
    ECGCNN_CONFIG_M, ECGAttNet_CONFIG_M,
    ECGCNN_CONFIG_L, ECGAttNet_CONFIG_L, 
    ECGCNN_CONFIG_XL, ECGAttNet_CONFIG_XL,
    ECGAttNet_CONFIG_XXL, ECGAttNet_CONFIG_130M
)

__all__ = [
    'ECGCNN', 'ECGAttNet',
    'ECGCNN_CONFIG_S', 'ECGAttNet_CONFIG_S',
    'ECGCNN_CONFIG_M', 'ECGAttNet_CONFIG_M',
    'ECGCNN_CONFIG_L', 'ECGAttNet_CONFIG_L',
    'ECGCNN_CONFIG_XL', 'ECGAttNet_CONFIG_XL',
    'ECGAttNet_CONFIG_XXL', 'ECGAttNet_CONFIG_130M'
]
'''
    # Overwrite the copied __init__.py with minimal version
    with open(EDGE_DUALNET_DIR / 'ecg_classification' / '__init__.py', 'w') as f:
        f.write(ecg_class_init)
    print("  ✓ ecg_classification/__init__.py (minimal for inference)")
    
    print("\n" + "=" * 60)
    print("✓ ECG-DualNet setup complete!")
    print("=" * 60)
    
    return True


if __name__ == '__main__':
    force = '--force' in sys.argv
    success = setup_ecg_dualnet(force=force)
    sys.exit(0 if success else 1)
